site_name: Doc Design Consulting
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Services: services.md
  - About: about.md
  - Portfolio:
    - Overview: portfolio/index.md
    - Canvas Docs-as-Code:
      - Case Study: portfolio/canvas-docs-as-code-public/case-study.md
#      - README: portfolio/canvas-docs-as-code-public/README_UPDATES.md
      - Explanation:
        - Why Docs-as-Code for Canvas?: portfolio/canvas-docs-as-code-public/explanation/why-docs-as-code.md
        - Large Language Models and Teaching: portfolio/canvas-docs-as-code-public/explanation/llms-and-teaching.md
        - Zotero Integration: portfolio/canvas-docs-as-code-public/explanation/zotero-integration.md
        - Single Sourcing Syllabi: portfolio/canvas-docs-as-code-public/explanation/single-sourcing-syllabi.md
      - How-To:
        - Set Up Canvas Docs-as-Code: portfolio/canvas-docs-as-code-public/how-to/setting-up.md
        - Use the Course Extractor: portfolio/canvas-docs-as-code-public/how-to/extracting-course.md
        - Attach and Manage Rubrics: portfolio/canvas-docs-as-code-public/how-to/using-rubrics.md
      - Reference:
        - Scripts: portfolio/canvas-docs-as-code-public/reference/scripts.md
#      - Publishing Documentation: portfolio/canvas-docs-as-code-public/PUBLISH_DOCUMENTATION.md
#      - Ideas: portfolio/canvas-docs-as-code-public/IDEAS.md
    - TRMNL My School Menus:
      - Overview and School Menu Lookup Tool: portfolio/trmnl-msm/index.md
    - Intervals.icu:
      - Overview: portfolio/intervals-icu/index.md
      - How-To:
        - Set Up the Script: portfolio/intervals-icu/how-to/setting-up.md
        - Plan Your Workouts: portfolio/intervals-icu/how-to/planning-workouts.md
        - Run the Script: portfolio/intervals-icu/how-to/running-the-script.md
      - Reference:
        - Scripts: portfolio/intervals-icu/reference/scripts.md
#  - Blog:
#    - First Post: blog/first-post.md
  - Contact: contact.md
