site_name: Doc Design Consulting
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Services: services.md
  - About: about.md
  - Portfolio:
    - Overview: portfolio/index.md
    - Canvas Docs-as-Code:
      - Case Study: portfolio/canvas-docs-as-code-public/case-study.md
#      - README: portfolio/canvas-docs-as-code-public/README_UPDATES.md
      - Explanation:
        - Why Docs-as-Code for Canvas?: portfolio/canvas-docs-as-code-public/explanation/why-docs-as-code.md
      - How-To:
        - Using Rubrics: portfolio/canvas-docs-as-code-public/how-to/using-rubrics.md
#      - Publishing Documentation: portfolio/canvas-docs-as-code-public/PUBLISH_DOCUMENTATION.md
#      - Ideas: portfolio/canvas-docs-as-code-public/IDEAS.md
#    - Intervals.icu: portfolio/intervals-icu/index.md
#  - Blog:
#    - First Post: blog/first-post.md
  - Contact: contact.md
